### ISSUE TITLE
Uses asset_path like methods in the asset pipeline

### ISSUE THREAD

**Issue by kdiogenes** [ruby2js/ruby2js#34]
I have a .js.rbs file. Is there anyway to use asset_path in it? I can't find a way to make it work.

**Comment by rubys** [comment]
I'm traveling so I'm not in a position to test this in a rails context, but backtics can be used to evaluate a ruby expression and place the result in the generated javascript code.  Essentially similar to the function that `<%=` and `%>` provides in erb.

An example:

```ruby
require 'ruby2js'

def asset_path(x)
  "//" + x
end

puts Ruby2JS.convert("path = `asset_path('foo').inspect`").to_s;
```

This generates the following

```javascript
var path = "//foo"
```

**Comment by rubydesign** [comment]
Cool, i didn't know you could do that.

If all else fails, one can do the thing that i often do to get data into a page, and that is:
-assign a javascript variable in the (erb/haml) page using to_json (or for strings just the strings)
-then use that variable in the rbs code

This is especially nice with the haml ruby2js filter (for small things)

**Comment by cerdiogenes** [comment]
In the asset pipeline I get the following error: `undefined method `image_path' for #<Ruby2JS::Converter:0x00007f144683f750>`

**Comment by rubys** [comment]
Any chance we can get a small-ish test case?  I'm traveling at the moment, so I may not get to this until early next week...but a test case may help speed this up.

**Comment by cerdiogenes** [comment]
Just created a simple Rails project: https://github.com/cerdiogenes/r2js-pipeline

**Comment by rubys** [comment]
That was helpful, and I hopefully pushed a fix: https://github.com/rubys/ruby2js/commit/07ea961e459ce345dba36c0e47bb949e27ed12ce.  I'm not closing this issue just yet; please verify that this addresses your problem.

Note: backtick operators will insert the value of the expression into the JavaScript directly.  In this case, it will produce a syntax error as there are no quotes.  Either put quotes around the backticks, or ensure that the expression itself produces a quoted string (perhaps by calling `.inspect` or `JSON.generate`).

**Comment by rubys** [comment]
@rubydesign why '.rbs'?  I would prefer '.rb' as many editors will recognize this extension and perform syntax highlighting.  Any objection to my changing this?

**Comment by cerdiogenes** [comment]
`.inspect` worked. ```"`image_path('snowflake.png')`"``` generates ```img.src = "`image_path('snowflake.png')`";```. I also tried ``` `"#{image_path('snowflake.png')}"` ```, it's gives `(eval):1: syntax error, unexpected tIDENTIFIER, expecting end-of-input "\""image_path("snowflake.png")"\""`

**Comment by rubydesign** [comment]
@rubys That is a small unfortunate side effect, yes. But it was quite simple to tell atom to use ruby for rbs too.
The reason was that ruby2js is not _really ruby, just ruby syntax, not semantics. So the s is for script, as in RubyScript. I also felt that opal (or the opal approach) rightfully owns the rb ending in the sprockets world, and with the s one can use both at the same time.

**Comment by rubys** [comment]
@cerdiogenes if you wanted to use double quotes, they would need to go outside of the backtics.

@rubydesign editors generally don't understand semantics, only syntax.  Opal allows JavaScript semantics to show through too (for example, strings are immutable), only less so.  Do people really use both together?  If not, I don't see a need for an unfortunate side effect.  I use .js.rb for most of my work (using Sinatra, not Rails); for example: https://github.com/rubys/ruby2js/issues/34#issuecomment-394053460

**Comment by rubydesign** [comment]
@rubys I meant since ruby2js code does not use ruby semantics one should not really call it ruby (.rb) in a setting where .rb could be used for ruby (opal conforms to ruby semantics really 99.9%). Your example, mutable strings, are bad style and will go in ruby 3.0. Off course there are minor others, but i have managed to run a 7k line project in opal with only one or two lines of change.

Since you don't use sprockets yourself, i guess it does not affect you. But off course you're the man.

**Comment by cerdiogenes** [comment]
@rubys I think you missed my observation about double quotes outside the backtics: ```"`image_path('snowflake.png')`"``` generates ```img.src = "`image_path('snowflake.png')`";```

**Comment by cerdiogenes** [comment]
@rubys I was tinkering the sprocket preprocessor and ended up with this:

```ruby
class SprocketProcessor
  def initialize( file)
    @file = file
  end
  def render(context , _)
    engine = ::ERB.new(File.read(@file), nil, '<>')
    input = engine.result(context.instance_eval('binding'))
    Ruby2JS.convert(input).to_s
  end
end
```

This allow to write the following in .rbs files: `img.src = "<%= image_path('snowflake.png') %>"`. I think it's better than the backticks.

**Comment by rubys** [comment]
@cerdiogenes Gotcha.  I'd like two changes: (1) continue to pass the context to the call to convert so that backtics will also work, and (2) make that opt-in, so if you want erb processing you get it.  The easiest way to make it opt-in would be to have two separate extensions, one for ruby2js only, and another for ruby2js+erb.  We probably should also create a bit of documentation :-)

Care to make one or more pull requests?

**Comment by cerdiogenes** [comment]
It will be a pleasure. I will follow the same organization as ruby2js/haml.rb

**Comment by rubys** [comment]
This looks promising: https://rossta.net/blog/testing-rails-generators.html

Unless you beat me to it, I'll look into it Monday-ish.
