### ISSUE TITLE
Allow for .rb file ending to be used in Sprockets

### ISSUE THREAD

**Issue by buhrmi** [ruby2js/ruby2js#37]
Hello,

first of all I really like the slickness of this gem.

I wanted to use it to share business logic between client and server. Assuming I have an `app/models/concerns/stats.rb`, which just defines a module. I want this Module object be available globally in my frontend Javascript, so in my `app/javascripts/application.js` I'd like to do something like `//= app/models/concerns/stats.rb` to share this functionality between Rails models and frontend.

Is there a good way to accomplish this? As far as I can tell, it's only possible to import `.rbs` file ending in javascript.

**Comment by rubydesign** [comment]
Hi @djshitcoin ,
when the sprockets processor was done .rbs was chosen as ruby2js is not complete ruby. So .rb was left for opal.
The code that does the registering of the .rbs is here https://github.com/rubys/ruby2js/blob/master/lib/ruby2js/rails.rb#L46 and if you want .rb in your app, you could copy that with .rb instead of .rbs

Or you can rename your file and get ruby (mri) to load the .rbs file (with load, possibly even require?)

**Comment by djshitcoin** [comment]
all right, monkey-patching it is :)

**Comment by rubys** [comment]
Actually, I'm open to changing this, based on actual usage.  Do we know of *anyone* who uses both opal and ruby2js?

**Comment by djshitcoin** [comment]
I think if you use ruby2js and opal in the same project you're doing something wrong...

**Comment by djshitcoin** [comment]
Hmm, even with monkey patching, the file ending needs to be `.js.rb`. Is there any way to tell sprockets to load the normal `something.rb` with javascript? I don't want to change the ending because then Rails' autoloading feature doesn't find the file anymore

**Comment by rubys** [comment]
Ruby2JS support reworked for Sprockets 4.0 registers both `.rb` and `.js.rb` extensions: https://github.com/ruby2js/ruby2js/blob/master/lib/ruby2js/sprockets.rb#L37
